name: Colin Wirt
favicon: null
layout_spectrum: 0.327572881244123
typography_spectrum: 0.7312719619367272
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.4456428410485387
  lightness: 0.25451324274763465
  saturation: 0.6272984051611274
  rhythmicContrast: 0.5195365431718528
purpose: []
